# Setup
title:               Paris Flood
tagline:             'As an Academic Website'
sidebar_text:        'Please <a href="/contact" title="Contact">reach out</a> if you ever feel the desire to do so!'
url:                 https://parisflo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Paris Flood
  twitter-username:  paris_flood
  github-username:   parisflo
#  url:               
# email:

# Gems
theme: jekyll-theme-lanyon
plugins:
  - jekyll-paginate

# Custom variables
version:             1.1.0
