# Setup
title:               Paris Flood
tagline:             'As an Academic Website'
description:         'Hello! My name is <a href="https://twitter.com/paris_flood" target="_blank">Paris Flood</a> and this is my personal website. It contains information about my scientific output as well as various tutorials related to my academic pursuits.'
url:                 https://parisflo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Paris Flood
  twitter-username:  paris_flood
  github-username:   parisflo
#  url:               
# email:

# Gems
theme: jekyll-theme-lanyon
plugins:
  - jekyll-paginate

# Custom variables
version:             1.1.0
